title: HackerNews Exploded
description: >-
  Sometimes there are hidden gems in HackerNews comments.

exclude: [CNAME, Gemfile, Gemfile.lock, README.md]
baseurl: ""
url: "https://hackernews-exploded.hadalin.me"

plugins:
  - jekyll-feed
